# Generated by Django 6.0.3 on 2026-04-05 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherwise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weathersearch',
            index=models.Index(fields=['user', '-searched_at'], name='weatherwise_user_id_9b92bf_idx'),
        ),
        migrations.AddIndex(
            model_name='weathersearch',
            index=models.Index(fields=['city'], name='weatherwise_city_29805b_idx'),
        ),
    ]
